# Generated by Django 2.2 on 2021-02-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MagicLinkHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('hits', models.IntegerField()),
            ],
        ),
    ]
